#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the countingValleys function below.
def countingValleys(n, s):
    count1 = 0
    valley = 0
    for items in s:
        if items == 'D':
            count1 -= 1
        elif items == 'U':
            count1 += 1
        if count1 == 0 and items == 'U':
            valley += 1
    return valley
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    s = input()

    result = countingValleys(n, s)

    fptr.write(str(result) + '\n')

    fptr.close()
